name: trackher
description: "A period tracking app for women"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.3
  dashed_circle: ^0.0.2
  intl: ^0.19.0
  font_awesome_flutter: ^10.8.0
  material_symbols_icons: ^4.2811.0
  shared_preferences: ^2.5.1
  flutter_svg: ^2.0.17
  flutter_switch: ^0.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1
  permission_handler: ^12.0.0+1
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  rename_app: ^1.6.2
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/avatars/
    - assets/posts/