// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnyYtLc4r_EgKSbF1bLQFrqAqQyAkN7n4',
    appId: '1:27623311684:web:477f111b2eeb0e2dc46f11',
    messagingSenderId: '27623311684',
    projectId: 'trackher-3e3e4',
    authDomain: 'trackher-3e3e4.firebaseapp.com',
    storageBucket: 'trackher-3e3e4.firebasestorage.app',
    measurementId: 'G-JR2N9Q8DVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ3VK0oZFGAv8fue0SFaFx75MjiBrtjE8',
    appId: '1:27623311684:android:f5bbae05f7affc73c46f11',
    messagingSenderId: '27623311684',
    projectId: 'trackher-3e3e4',
    storageBucket: 'trackher-3e3e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkTj717iEJ5rTzrcGZyYJeIZm1ESHiQcc',
    appId: '1:27623311684:ios:79e08352f719ad31c46f11',
    messagingSenderId: '27623311684',
    projectId: 'trackher-3e3e4',
    storageBucket: 'trackher-3e3e4.firebasestorage.app',
    iosBundleId: 'com.zynth.trackher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkTj717iEJ5rTzrcGZyYJeIZm1ESHiQcc',
    appId: '1:27623311684:ios:79e08352f719ad31c46f11',
    messagingSenderId: '27623311684',
    projectId: 'trackher-3e3e4',
    storageBucket: 'trackher-3e3e4.firebasestorage.app',
    iosBundleId: 'com.zynth.trackher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnyYtLc4r_EgKSbF1bLQFrqAqQyAkN7n4',
    appId: '1:27623311684:web:f166bcd2333246b0c46f11',
    messagingSenderId: '27623311684',
    projectId: 'trackher-3e3e4',
    authDomain: 'trackher-3e3e4.firebaseapp.com',
    storageBucket: 'trackher-3e3e4.firebasestorage.app',
    measurementId: 'G-BBY42GCLKN',
  );
}
